name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
        
      - name: Run install root
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install  --frozen-lockfile` command
        env:
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          EMAIL_FROM: ${{ env.EMAIL_FROM }}
          REACT_APP_THIN_BACKEND_SERVER_URL: ${{ env.REACT_APP_THIN_BACKEND_SERVER_URL }}
          REACT_APP_BLOG_SERVER_URL: ${{ env.REACT_APP_BLOG_SERVER_URL }}

      - name: Run install in thin-backend 
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
          dir: 'thin-backend' # will run `yarn install --frozen-lockfile` in `thin-backend` sub folder
  
  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

  test:
    needs: [install, build]
    runs-on: ubuntu-latest
    steps:
      - name: Test React
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command

  deploy:
    needs: [install, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: main
          publish_dir: ./build
