name: Production CI
on:
  push:
    branches:
      - main

jobs:
  call-base-workflow:
    uses: ./.github/workflows/base.yml

  deploy:
    runs-on: ubuntu-latest
    needs: call-base-workflow
    steps:
      - name: deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
