name: Production CI
on:
  push:
    branches:
      - main

jobs:
  call-base-workflow:
    uses: ./.github/workflows/base.yml

  deploy:
    environment:
      name: gh-pages
    runs-on: ubuntu-latest
    needs: call-base-workflow
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            node_modules
            thin-backend/node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('yarn.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('yarn.json') }}

      - name: Get root build
        uses: actions/download-artifact@v3
        with:
          name: save-state-with-build
          path: build

      - name: Deploy build folder to production
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
