name: Production CI
on:
  push:
    branches:
      - main

jobs:
  call-base-workflow:
    uses: ./.github/workflows/base.yml

  deploy:
    environment:
      name: gh-pages
    runs-on: ubuntu-latest
    needs: call-base-workflow
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            node_modules
            thin-backend/node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}

      - name: Setup git
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: deploy # will run `yarn build` command
