name: Production CI
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-base-workflow:
    uses: ./.github/workflows/base.yml

  deploy:
    environment:
      name: gh-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: call-base-workflow
    steps:
      - uses: actions/checkout@v3

      - name: get root build
        uses: actions/download-artifact@v3
        with:
          name: save-state-with-build
          path: build

      - name: deploy build folder to production
        id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: build
