name: Frontend WorkFlows
on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install root
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install  --frozen-lockfile` command

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:frontend # will run `yarn build:frontend` command

      - name: Upload current build
        uses: actions/upload-artifact@v3
        with:
          name: save-frontend-build
          if-no-files-found: error
          path: build

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}

      - name: Test React
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
