name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  thin_backend:
    uses: ./.github/workflows/thin_backend.yml

  frontend:
    uses: ./.github/workflows/frontend.yml

  deploy:
    runs-on: ubuntu-latest
    if: github.event.push
    needs: [thin_backend, frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Thin-Backend NPM dependencies
        uses: actions/cache@v3
        id: yarn-thin-backend-cache
        with:
          path: |
            ./thin-backend/node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./thin-backend/package.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./thin-backend/package.json') }}

      - name: Cache Frontend NPM dependencies
        uses: actions/cache@v3
        id: yarn-frontend-cache
        with:
          path: node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-${{ hashFiles('./package.json') }}

      - name: Get frontend build
        uses: actions/download-artifact@v3
        with:
          name: save-frontend-build
          path: build
